### PR TITLE
add hacka lumpur

### PR DESCRIPTION
**Pull request by T31K**
also changed the year for hackapura.

thanks 🙏🏻

### CODE REVIEW

**Comment by T31K** [comment]
@drpancake

**Comment by drpancake** [comment]
@T31K nice! there's an extra </a> tag in there that's making it render weird.

also would you be cool with sticking to the one word naming "Hackalumpur" ?

**Comment by T31K** [comment]
> @T31K nice! there's an extra tag in there that's making it render weird.
> 
> also would you be cool with sticking to the one word naming "Hackalumpur" ?

gotcha. updated!

**Comment by T31K** [comment]
Oh stupid me, there was an extra `<a>` tag, should be working now. Thanks!

**Pull request merged**
